<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ZauberCMS\ZauberCMS.csproj" />
      <!--<PackageReference Include="ZauberCMS" Version="4.0.0-rc.5.4" />-->
    </ItemGroup>
    
    
    <ItemGroup>
      <Folder Include="Logs\" />
      <Folder Include="wwwroot\media\" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="app.db" />
    </ItemGroup>
    
</Project>