<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>ZauberCMS.Core</PackageId>
        <Version>4.0.0-rc.5.1</Version>
        <Authors>Lee Messenger</Authors>
        <Description>ZauberCMS core package</Description>
        <PackageTags>Web</PackageTags>
        <LocalNugetSource>$(MSBuildProjectDirectory)\..\NugetSource</LocalNugetSource>
        <PackageProjectUrl>https://github.com/YodasMyDad/ZauberCMS</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/YodasMyDad/ZauberCMS</RepositoryUrl>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
    
        <PackageReference Include="Blazored.Modal" Version="7.3.1" />
        <PackageReference Include="FluentValidation" Version="12.0.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="HtmlSanitizer" Version="9.0.886" />
        <PackageReference Include="MailKit" Version="4.14.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="9.6.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Radzen.Blazor" Version="8.0.2" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="ImageResize" Version="2.0.0" />
        <PackageReference Include="ZauberCMS.RTE" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\PostgreSql\" />
      <Folder Include="Data\Migrations\SqLite\" />
      <Folder Include="Data\Migrations\SqlServer\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Data\Migrations\SqlServer\ZauberDbContextModelSnapshot.cs" />
    </ItemGroup>

    <Target Name="CopyNuGetPackage" AfterTargets="Pack">
        <PropertyGroup>
            <PackageOutputDir>$(OutputPath)..\</PackageOutputDir>
            <GeneratedPackage>$(PackageOutputDir)\$(PackageId).$(Version).nupkg</GeneratedPackage>
        </PropertyGroup>
        <Copy SourceFiles="$(GeneratedPackage)" DestinationFolder="$(LocalNugetSource)" />
    </Target>
    
</Project>

























