<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" Version="10.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>build</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ZauberCMS" Version="4.1.2"/>
    </ItemGroup>
    
</Project>







































